sudo: false
dist: trusty
language: ruby
cache:
  bundler: true
  directories:
    - node_modules
script: bundle exec rake build test
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"
  on:
    repo: shipcloud/shipcloud.github.io
    branch: master
  skip_cleanup: true
notifications:
  flowdock:
    secure: JoghBZRgtGMnBFdvp/bfkVaAKwYs7qr8bQ7RByLVWzh9qxrzsdACcWo9vyhaLc7KOp+C2wkxlYHs5NGWo+3sHjdHG7ZGwTFXrGnzSiXcm7hcSM/cNAR+nNDzrt/KfrOGA4vc8zZWuD6R1OpmcPwa9x5ZCMxsRT1F1BqR2RDlcoE=
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
