# Site settings
title: shipcloud.io - Developer Portal
email: developers@shipcloud.io
description: >
  The shipcloud.io developer portal is your one stop for all developer needs.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://andrecedik.github.io/shipcloud.github.io" # the base hostname & protocol for your site
twitter_username: shipcloud_devs
github_username:  shipcloud
integration_guide_url:
  de: >
    https://www.dropbox.com/s/klycgg1p1d3v20v/shipcloud_integration_guide_de.pdf?dl=0
  en: >
    https://www.dropbox.com/s/dgi9r9w8p40snuu/shipcloud_integration_guide_en.pdf?dl=0
shipcloud:
  supported_carriers:
    as_display_names: 'DHL, DHL Express, Deutsche Post, UPS, DPD, Hermes, GLS, MyDPD Business (iloxx), TNT, FedEx, GO!, PARCEL.ONE, Seven Senders und Cargo International'
    as_keys: '"dhl", "dhl_express", "dpag", "ups", "dpd", "hermes", "gls", "iloxx", "tnt", "fedex", "go", "parcel_one", "seven_senders" and "cargo_international"'
    as_keys_array: '"dhl", "dhl_express", "dpag", "ups", "dpd", "hermes", "gls", "iloxx", "tnt", "fedex", "go", "parcel_one", "seven_senders", "cargo_international"'
    as_list: 
      - 
        name: DHL
        key: dhl
      - 
        name: DHL Express
        key: dhl_express
      - 
        name: Deutsche Post
        key: dpag
      - 
        name: UPS
        key: ups
      - 
        name: DPD
        key: dpd
      - 
        name: Hermes
        key: hermes
      - 
        name: GLS
        key: gls
      - 
        name: MyDPD Business (iloxx)
        key: iloxx
      - 
        name: TNT
        key: tnt
      - 
        name: FedEx
        key: fedex
      - 
        name: GO!
        key: go
      - 
        name: PARCEL.ONE
        key: parcel_one
      - 
        name: Seven Senders
        key: seven_senders
      - 
        name: Cargo International
        key: cargo_international
    carrier_features:
      hermes:
        props:
          additional_services:
            - 
              name: Cash on delivery
              key: cash_on_delivery
          field_lengths:
            - first_name: 0 - 30 caracters
            - last_name: 1 - 25 characters
            - company: 2 - 50 characters
            - care_of: 0 - 50 characters
            - street: 1 - 27 characters
            - street_no: 0 - 5 characters
            - zip_code: (country specific checks by carrier)
            - city: 1 - 30 characters
            # - foo: {
            #   a: b
            # }
          label_sizes:
            - 
              name: DIN A5
              key: A5
          package_types:
            - 
              name: Bulk
              key: bulk
            - 
              name: Parcel
              key: parcel
          services:
            - 
              name: Returns
              key: returns
            - 
              name: Standard
              key: standard
        hsi:
          additional_services:
            - 
              name: Advance Notice
              key: advance_notice
            - 
              name: Ident Check
              key: hermes_ident_check
            - 
              name: Next Day Delivery
              key: hermes_next_day
          field_lengths:
            - first_name: 0 - 20 characters
            - last_name: 1 - 30 characters
            - company: 0 - 20 characters
            - care_of: 0 - 20 characters
            - street: 1 - 27 characters
            - street_no: 1 - 5 characters
            - zip_code: 1 - 8 characters
            - city: 1 - 30 characters
          label_sizes:
            - 
              name: DIN A5
              key: A5
            - 
              name: DIN A6
              key: A6
          package_types:
            - 
              name: Bulk
              key: bulk
            - 
              name: Parcel
              key: parcel
          services:
            - 
              name: Returns
              key: returns
            - 
              name: Standard
              key: standard
        supported_services:
          as_keys_array: '"standard", "one_day" , "one_day_early", "cargo_international_express", "ups_express_1200", "dhl_europaket", "returns"'

# Build settings
markdown: kramdown
# kramdown:
#   auto_ids: false

apikey: be51608682014a3adf620fc252d63390

sass:
  sass_dir: _sass
  # style: :compressed

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

exclude:
  - vendor
  - divshot.json
  - node_modules
